steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        REPO_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        pack build \
          $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_LOWER/$_SERVICE_NAME:$COMMIT_SHA \
          --builder=gcr.io/buildpacks/builder:latest \
          --publish

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _SERVICE_NAME: brand-book-backend