steps:
  # Use the official Google Cloud SDK to run the buildpack
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud builds submit . \
          --pack image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          --service-account=projects/$PROJECT_ID/serviceAccounts/backend-api-brandbook@$PROJECT_ID.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _SERVICE_NAME: brand-book-backend # Change this to your preferred service name