steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pack build \
          $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')/$_SERVICE_NAME:$COMMIT_SHA \
          --builder=gcr.io/buildpacks/builder:latest \
          --publish

  # CHECK LINE 20 HERE: Make sure there is a dash and a space before "name"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _SERVICE_NAME: brand-book-backend